### ISSUE TITLE
Request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by ping0xFF** [adosztal/gns3-containers#1]
I'm using GNS3 and installed the Networkers' Toolkit appliance from GNS3 marketplace. 

When I drag Toolbox from the available appliances to the main window, I received the following:

```
Pulling 'adosztal/net_toolbox:latest' from docker hub
Error while creating node: Docker has returned an error: 500 Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by adosztal** [comment]
Oh sorry, I missed this somehow. This is usually an intermittent issue on Docker Hub and has nothing with the container itself. Try downloading it again later.
