### ISSUE TITLE
Issue when using aaa authorization

### ISSUE THREAD

**Issue by ghost** [adosztal/gns3-containers#2]
when authorization configure on cisco router, cannot enable device:

```
root@AAA-1:~# telnet 10.0.0.1
Trying 10.0.0.1...
Connected to 10.0.0.1.
Escape character is '^]'.


User Access Verification

Username: gns3
Password: 

R1>en
% Error in authentication.

R1>
```

Debug from device:

`*Apr 20 21:31:36.305: TPLUS: Failed to decode unknown AV priv_lvl=15 - FAIL`

Looks like an issue in /etc/tacacs+/tac_plus.conf:

```
root@AAA-1:~# grep priv /etc/tacacs+/tac_plus.conf 
		priv_lvl = 15
		priv-lvl = 15
root@AAA-1:~#
``` 

Change priv_lvl  to priv-lvl in etc/tacacs+/tac_plus.conf:

```
root@AAA-1:~# sed -i s/priv_lvl/priv-lvl/g /etc/tacacs+/tac_plus.conf 
root@AAA-1:~# /etc/init.d/tacacs_plus restart
 * Restarting TACACS+ authentication daemon tacacs+                                             [ OK ] 
root@AAA-1:~# telnet 10.0.0.1
Trying 10.0.0.1...
Connected to 10.0.0.1.
Escape character is '^]'.


User Access Verification

Username: gns3
Password: 

R1#
```

**Comment by adosztal** [comment]
Thank you! I pushed the fix, the container will be built soon.

**Comment by adosztal** [comment]
New image is available on Docker Hub. Could you test it?

**Comment by ghost** [comment]
I tried to install it from gns3 from available and same (private_lvl)
Downloaded from gns3 marketplace, same thing.

Maybe they have to sync…or there is another way for me to get it in there (gns3) that I didn’t think about.

**Comment by adosztal** [comment]
Container image update is a missing feature in GNS3 (but the guys are working on it). You should remove the image by entering `docker rmi adosztal/aaa:latest` where you run the containers (GNS3 VM, your local box, or a remote GNS3 server), then import the appliance again.

**Comment by ghost** [comment]
Works like a charm.

Thanks.
