### ISSUE TITLE
Network automation: Invalid ssh cipher blowfish-cbc

### ISSUE THREAD

**Issue by ghost** [adosztal/gns3-containers#5]
GNS3 community: https://gns3.com/community/discussion/network-automation-bad-ssh2-ciph

SSH doesn't work since update to ubuntu/bionic:

```
root@NetworkAutomation-1:~# ssh 192.168.122.72
/root/.ssh/config line 2: Bad SSH2 cipher spec '3des-cbc,blowfish-cbc,aes128-cbc,aes128-ctr,aes256-ctr'.
```

Cipher `blowfish-cbc` is invalid in the bionic version of ssh.

**Comment by adosztal** [comment]
Thanks!
